---
- name: Check for /usr/bin/yarn presence
  ansible.builtin.stat:
    path: /usr/bin/yarn
  register: yarn_installed

- name: Install yarn
  community.general.npm:
    name: yarn
    global: true
  when: not yarn_installed.stat.exists

- name: Install Mastodon dependencies
  ansible.builtin.command: "yarn install --immutable"
  args:
    chdir: /opt/mastodon
  become_user: mastodon
  environment:
    RAILS_ENV: production
    COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"

- name: Check if Mastodon assets are already installed
  ansible.builtin.stat:
    path:  /opt/mastodon/public/assets
  register: mastodon_assets_installed

- name: Precompile Mastodon assets
  ansible.builtin.command: "bin/rails assets:precompile"
  args:
    chdir: /opt/mastodon
  become_user: mastodon
  environment:
    RAILS_ENV: production
    NODE_ENV: production
    LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu

# bundle exec rails webpacker:install
# Elasticsearch indexes: deployed at end of role via tootctl search deploy
